### ISSUE TITLE
Add Meeting Notes Page

### ISSUE THREAD

**Issue by brianpham** [typeobject/commhill-org#12]
One common issue I see coming up time and time again is what was discussed during the HOA meetings / Communications Hill meetings. 

A nice to have would be to include a meetings note page that has a quick recap of discussions that occurred, any action items, to do, etc.

**Comment by bringhurst** [comment]
I'm under the impression that many of the HOA meeting notes are intended for homeowner access only -- so the HOA management company might be better suited to maintain those notes.

That said, if the HOA approves of public display and wants it here, I'd be happy to host it.

**Comment by bringhurst** [comment]
It might be useful to repost some of the items in HOA newsletters that apply (mostly) to everyone. For example, the Tuscany Hills newsletter tends to have one or two things that would be appropriate.

**Comment by brianpham** [comment]
Good point, might have to be more appropriate for everyone

**Comment by bringhurst** [comment]
Going to close this one as won't fix for now -- we can followup with tickets that includes the specific content.
