### ISSUE TITLE
Suggestion: San Jose 311 App Download Link

### ISSUE THREAD

**Issue by angelhuang** [typeobject/commhill-org#8]
I find it more useful to have the app. A quick link to download via iphone or android would be useful. 
iphone: https://apps.apple.com/us/app/my-san-jose-a-newway/id1231429879
android: https://play.google.com/store/apps/details?id=com.astcorporation.three11&hl=en

**Comment by bringhurst** [comment]
Agreed -- although the current page indirectly does link to these, it's a few clicks away before it can be found. We should have direct links.

**Comment by bringhurst** [comment]
Closed by #16
